### PR TITLE
Dev logic milestone 3, request for code review

### PR DESCRIPTION
**Pull request by wickathou**
Added complete game logic

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello @wickathou 

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

- There should be a **lib** folder that has all the different logic and class files as well as a **bin** folder with a **main.rb** file, which you have but it's empty.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes required.

Hi wickathou!

Everything looks good, just few changes, 

1. In milestone 2, you had this requirement:
    -  main.rb uses puts/print and get.chomp commands. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/) )

In summary, make your main.rb file handle code that interfaces with the user, such as asking user to choose a symbol, selecting a valid move, printing results for the user. Consequently, in your lib folder, the methods should be returned.


2.  Use only attr_readers/attr_writers instead of attr_accessors for this project. This is because, by using attr_accessors you allow writing the property from outside the class. The variable can be set to anything.
 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))


                We want the student to understand the implication of using attr_accessors.

After implementing these changes submit another form for a code review.

#### ``` Have a great ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @wickathou  , 👋 , Few things to do 

##### Implementation details

* [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] All classes are kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))


----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

_If you have any queries, feel free to ping me on slack_

**Comment by wickathou** [comment]
The issue is that I made this long time ago and I didn't on another way. I am seriously tired of the whole situation, I been stuck for already 2 months and without a partner and I don't feel like remaking the whole program again to have the main.rb with all the puts and gets.

Could you tell me why the main.rb should have all the puts/gets?

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @wickathou :wave: . 
Really sorry to hear that you are working alone and that wasted your precious time :disappointed: . But at the same time really happy for you that you approved yourself as not a quitter :sunglasses: . 
> The issue is that I made this long time ago and I didn't on another way. I am seriously tired of the whole situation, I been stuck for already 2 months and without a partner and I don't feel like remaking the whole program again to have the main.rb with all the puts and gets.
> 
> Could you tell me why the main.rb should have all the puts/gets?
___
The ans is really simple. The core feature of OOP is SOLID methodologies/principals. The first one is Single Responsibility Principle. Which is, in a simple form, A class should only have one responsibility, which is further defined by Martin as ‘one reason to change’.
So this project is divided into several part based on it. Board should be responsible to store the property and action related to board, player to possess the functionality a player should have and main to handle the UI based on game's logic. If you need more info feel free to schedule a one to one session with TSE through Student success.
___
### :space_invader: [!! Mandatory Changes !!] :space_invader: 
___
1. On the bin I can see two main, one with .rb extension. That one is needed.
2. No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
I can see some on your player class.
___
### :clubs: [Optional Changes] :clubs: 
___
1. Well there is still some spaces to make the code more refactor-able.
___
##### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by wickathou** [comment]
Alright, I understand it now, but I basically need to remake the whole thing and I don't really feel like it.

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello @wickathou   🌟

**Good work so far, you only need to fix the following before the milestone can be approved ⬇️**

- There should be no `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](
https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Pull request closed without merging**
